ph2_qcc:
  P_Pa:
    method: minmax
  T_K:
    method: minmax
  cp:
    method: minmax
  cs2:
    method: maxval
  drdP:
    method: standard
  drdT:
    method: standard
  g:
    method: minmax
  gamma:
    method: standard
  h:
    method: minmax
  rho:
    method: maxval
  s:
    method: minmax
  u:
    method: minmax
