activation: srelu3
batch_size: 32
eos: ph2_qcc
epochs: 10
inputs:
- T_K
- P_Pa
loss_weights:
  drdP: 0.01
  drdT: 0.01
  rho: 1.0
lr: 2.0e-06
n_hidden:
- 16
- 8
- 4
phase: liquid
property: rho
srelu_eps: 1.0
use_deriv_loss: false
